language: node_js
node_js:
  - "8"
install: npm install
jobs:
  include:
    - stage: ESLint
      script: npm test
    - stage: Mocha
      script: npm run mocha-test

notifications:
  webhooks:
    urls:
      - https://api.discordspark.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  email: false
